[versions]
minecraft = "1.18.2"
fabric-loader = "0.13.3"
yarn-mappings = "1.18.2+build.2"

fabric-api = "0.47.10+1.18.2"

# Kotlin
kotlin = "1.6.10"
fabric-kotlin = "1.7.1+kotlin.1.6.10"

# Discord
kord-extensions = "1.5.3-SNAPSHOT"
mc-discord-reserializer = "4.2.2"
emoji-java = "5.1.1"
adventure-fabric = "5.2.0"
adventure-gson = "4.10.1"

placeholder-api = "1.1.3+1.17.1"
permission-api = "0.1-SNAPSHOT"
konf = "1.1.2"

styled-chat = "1.2.2+1.18"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
emoji = { module = "com.vdurmont:emoji-java", version.ref = "emoji-java"}
mcDiscordReserializer = { module = "dev.vankka:MCDiscordReserializer", version.ref = "mc-discord-reserializer"}
adventure-fabric = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-fabric"}
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure-gson"}

placeholder-api = { module = "eu.pb4:placeholder-api", version.ref = "placeholder-api" }
permission-api = { module = "me.lucko:fabric-permissions-api", version.ref = "permission-api"}
konf-base = { module = "com.uchuhimo:konf-core", version.ref = "konf" }
konf-toml = { module = "com.uchuhimo:konf-toml", version.ref = "konf" }

styled-chat = { module = "maven.modrinth:styled-chat", version.ref = "styled-chat" }
