[versions]
minecraft = "24w09a"
fabric-loader = "0.15.7"
yarn-mappings = "24w09a+build.6"

fabric-api = "0.96.5+1.20.5"

# Kotlin
fabric-kotlin = "1.9.4+kotlin.1.8.21"

# Discord
kord-extensions = "1.5.6"
mc-discord-reserializer = "4.3.0"
emoji-java = "5.1.1"
adventure-gson = "4.15.0-SNAPSHOT"

placeholder-api = "2.3.0+1.20.3"
permission-api = "0.3-SNAPSHOT"
vanish-api = "1.5.1+1.20.4"
konf = "1.1.2"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
emoji = { module = "com.vdurmont:emoji-java", version.ref = "emoji-java"}
mcDiscordReserializer = { module = "dev.vankka:mcdiscordreserializer", version.ref = "mc-discord-reserializer"}
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure-gson"}

placeholder-api = { module = "eu.pb4:placeholder-api", version.ref = "placeholder-api" }
permission-api = { module = "me.lucko:fabric-permissions-api", version.ref = "permission-api"}
vanish-api = { module = "maven.modrinth:vanish", version.ref = "vanish-api"}
konf-base = { module = "com.uchuhimo:konf-core", version.ref = "konf" }
konf-toml = { module = "com.uchuhimo:konf-toml", version.ref = "konf" }
